pipeline:
  name: Build playgroundJS
  identifier: Build_keen_software_playgroundJS_1780946531977
  projectIdentifier: Nofar_Test_Templates
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.github
        repoName: keen-software/playgroundJS
        build: <+input>
  notificationRules:
    - name: test
      identifier: test
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: https://webhook.site/bfa015d0-3319-492f-a4a8-4a1601d345e4
          headers:
            TEST: <+ "hello world" >
      enabled: true
